### PR TITLE
(maint) Merge branch '6.x' into 'main'

### PR DESCRIPTION
**Pull request by justinstoller**
Conflicts:
  - acceptance/config/beaker/options.rb

### CODE REVIEW

**Comment by mwaggett** [comment]
It concerns me that this stopped working..

**Review by mwaggett — APPROVED** [review]

**Comment by justinstoller** [comment]
I think it's weird that [this build](https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppetserver_puppetserver-mergeup_6.x/46/) failed on this kind of merge up, but we were doing a lot of merge ups yesterday/last night. So I'll try this again and tonight's merge up fails I'll investigate more thoroughly.

**Review by Magisus — APPROVED** [review]

**Comment by mwaggett** [comment]
@justinstoller I think this is the second mergeup like this that has failed since my changes 😞

**Comment by justinstoller** [comment]
Then I guess I'll go ahead and look into more this afternoon  ( ;

**Comment by justinstoller** [comment]
I should have put a skip CI on this. there's nothing travis is going to tell us about this merge up.

**Pull request merged**
