### PR TITLE
(server-1870) add ci job for automatically bumping puppet submodule commit

### PR DESCRIPTION
**Pull request by er0ck**
* merge-up from 5.0.x
* update pin from `5.0.x` to `master`

### CODE REVIEW

**Comment by MosesMendoza** [comment]
I'm not familiar yet with the workflow on puppet-server so forgive me for the noob question - but why cherry-pick from 5.0.x to master, instead of merging 5.0.x to master? Is master not ahead of 5.0.x?

**Comment by er0ck** [comment]
yeah, i probably should have.  but i had to update the constant to master after that commit.  i didn't think it mattered really.  if people prefer, i can certainly merge, instead

**Comment by MosesMendoza** [comment]
@er0ck would you mind? I admit i'm a bit pedantic - it would be great to avoid the duplicate commit that we'll have when we do the next merge-up after this cherry-pick, just to keep the history clean. I personally prefer `--no-ff --log` flags to the merge so its clear what the merge-up contained too.

**Comment by er0ck** [comment]
no problemo.

**Pull request merged**
