### PR TITLE
(doc) Fix and update links in environment_classes doc

### PR DESCRIPTION
**Pull request by gguillotte**
Resolves DOC-2704.

### CODE REVIEW

**Comment by camlow325** [comment]
🙈 @gguillotte - are you okay with these changes only being on our master branch or would you like them on our stable branch as well?  I can't say for sure whether or not any new releases will be done from the current incarnation of our stable branch.  Also, do you think anyone else from the docs team needs to look at this before we'd merge it?

**Comment by gguillotte** [comment]
@camlow325 Yeah, I should have probably targeted this at stable. The changes should be on both branches. I can close and refile against stable if that'd be easier.

**Comment by camlow325** [comment]
@gguillotte Yeah, if you want the changes on both branches, it would be better to target them at stable so that they get merged up from their to the master branch.  We don't often do full branch merges in the other direction.

**Comment by rlinehan** [comment]
@gguillotte @camlow325 we're about to do a merge down of master to table for the release, so maybe this is actually okay? Unless we ever might need to pin something to stable at a SHA before the merge down and that would need to include this.

**Comment by camlow325** [comment]
Yeah, assuming it's probably unlikely that we'll resurrect a 2.3.x branch for a special release later and would want these changes to go in the docs for that, I think it might be better to just put this in the master branch.  @rlinehan - if you want to just merge this now and @gguillotte is good with that, I'm 👍 as well.

**Comment by gguillotte** [comment]
:+1:

**Pull request merged**
