### PR TITLE
(maint) Merge '5.3.x' into '6.0.x'

### PR DESCRIPTION
**Pull request by justinstoller**
```
Conflicts:
  - acceptance/config/beaker/options.rb
  - dev/dev_tools.clj
```

### CODE REVIEW

**Comment by justinstoller** [comment]
don't know if we want to wait for 5.3.x to go through CI first

**Comment by Magisus** [comment]
Maybe at least the failed step. Though I would like to get this merged up before the holiday if possible, so we have a chance at green runs across the board.

**Comment by Magisus** [comment]
Cells are starting to go green in 5.3.x, merging.

**Comment by justinstoller** [comment]
I just came to this PR to say the same thing!

**Pull request merged**
