### PR TITLE
(SERVER-1807) Update Hocon to 1.2.5

### PR DESCRIPTION
**Pull request by Iristyle**
- 1.2.5 addresses loading files with UTF-8 characters in their path

### CODE REVIEW

**Comment by Iristyle** [comment]
@rlinehan @camlow325 I'm not sure how your branches work.  I know that this change needs to coincide with the Puppet 5 release.  I'm uncertain if this repo takes changes to stable and merges them up to master?  On that assumption I've targeted stable, assuming this will be merged up.

If that's not how this repo works, feel free to re-target the PR at master branch instead.

**Comment by rlinehan** [comment]
@Iristyle for puppet server 5, changes should go on master. For puppet server 2.7.x, changes should go on stable. When we get to release time for puppet server 5 we'll merge down master to stable.

**Comment by Iristyle** [comment]
Thanks @rlinehan - updated.

/cc @LarissaLane on this one.

**Comment by camlow325** [comment]
@Iristyle Yeah, unless you think we're going to need this for use with Puppet 4.x / Puppet-Agent 1.x, I think it would be better to just target this at the master branch for Puppet 5.  I'm honestly not sure if we'll need to do another Puppet Server 2.x release at this point and, even if so, I suspect that the vendored gems wouldn't be exercised via pre-Puppet 5 code anyway.

**Comment by LarissaLane** [comment]
This is great!

**Comment by adrienthebo** [comment]
I'm going to build a package based on this PR and verify that we get the gem appropriately bundled, as long as that goes well I'll approve/merge.

**Comment by camlow325** [comment]
@adrienthebo - did you get a chance to try this out in a build?  Are you good with merging this?

**Comment by adrienthebo** [comment]
@camlow325 I haven't been able to complete a build, having issues with access to the build servers - I'll follow up on this as soon as I can actually log in.

**Pull request merged**
