### PR TITLE
(PE-30968) Include the builtin bolt content's pluginsync

### PR DESCRIPTION
**Pull request by ekinanp**
Signed-off-by: Enis Inan <enis.inan@puppet.com>

### CODE REVIEW

**Comment by ekinanp** [comment]
I have no idea why this PR's failing the Azure build. Seems like something's up with the Docker daemon there?

**Comment by ekinanp** [comment]
Also, I don't think this needs any more testing than what's here since the integration tests provide good coverage. So this means, for example, that we probably don't need any new Orch-side acceptance tests.

**Comment by ekinanp** [comment]
I'm also not sure what's causing the other, Docker container CI failure.

**Review by McdonaldSeanp — APPROVED** [review]

**Comment by McdonaldSeanp** [comment]
Will merge pending tests

**Comment by ekinanp** [comment]
Cool, looks like this is good to go now.

**Pull request merged**
