### PR TITLE
(maint) Infra CRL improvements

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
I think the first two commits are the right code changes, however I rushed and did this backwards and don't have the tests working correctly now.

**Comment by Magisus** [comment]
I agree that the code changes look right. That explains the bug we were seeing too. Looking into the tests now.

**Comment by justinstoller** [comment]
Okay, I also did a functional test that you can successfully revoke the CA's cert and have it exist both CRLs.

**Comment by Magisus** [comment]
Sweet.

**Pull request merged**
