### PR TITLE
(SERVER-1505) Pre docs for the status endpoint

### PR DESCRIPTION
**Pull request by camlow325**
This commit provides some pre-docs for the status endpoint.

### CODE REVIEW

**Comment by camlow325** [comment]
@gguillotte - would appreciate it if you could take a peek at this if you have time.  If not, we could merge it and have you just do your second pass later.

fyi, I lifted quite a bit of the detailed docs for this from the [trapperkeeper-status docs](https://github.com/puppetlabs/trapperkeeper-status/blob/0.3.5/documentation/query-api.md).

**Comment by camlow325** [comment]
Merged in a commit with some changes from @gguillotte at b967deb.

**Comment by gguillotte** [comment]
:+1:

**Comment by jpinsonault** [comment]
👍

**Pull request merged**
