### PR TITLE
Merge 5.3.x -> 6.0.x

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by justinstoller** [comment]
Do we want to include these[1] changes into 6.0.x? Or should we switch to jdk11?


1. https://github.com/puppetlabs/puppetserver/blob/master/.travis.yml#L4-L11

**Comment by Magisus** [comment]
Would including that get Travis passing?

**Comment by justinstoller** [comment]
I think so

**Comment by Magisus** [comment]
I'll pull them in. We can do the jdk11 thing separately.

**Pull request merged**
