### PR TITLE
(maint) Mergeup 6.3.x to master

### PR DESCRIPTION
**Pull request by Iristyle**

### CODE REVIEW

**Comment by Magisus** [comment]
Can we wait on https://github.com/puppetlabs/puppetserver/pull/2029 to merge this please?

**Comment by Iristyle** [comment]
@Magisus master will keep Azure-ing... but 6.x series drops the Azure-ing :)

**Comment by Magisus** [comment]
Our of curiosity, why the difference?

**Comment by Iristyle** [comment]
We're restricting builds to run only on the branches that we're actively contributing to - that's just `master` for now.

**Pull request merged**
