### PR TITLE
(SERVER-2090) Increase resiliency of metrics test

### PR DESCRIPTION
**Pull request by haus**
As we've seen the metrics test occasionally fail with an error about
reaching the graphite service, this commit adds a call to ensure httpd
itself is running and then a 5 minute poll (in 5 second intervals), to
wait for it to start up before querying it.

### CODE REVIEW

**Comment by haus** [comment]
Side note: I'm not convinced we should keep this test. I don't think we've ever seen it fail except from transient not code related issues.

**Comment by haus** [comment]
```
acceptance/suites/tests/metrics/collect_default_metrics.rb passed in 195.28 seconds
      Test Suite: tests @ 2018-03-01 14:07:47 -0800

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 195.29 seconds
      Average Test Time: 195.29 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

No tests to run for suite 'post_suite'
No tests to run for suite 'pre_cleanup'
Cleanup: cleaning up after successful run
ssh connection to redhat7-64-1 has been terminated
ssh connection to redhat7-64-2 has been terminated
Handing 'ro5fqs3n8lp2no5.delivery.puppetlabs.net' back to vmpooler for VM destruction
Handing 'ekagz9f8djc0gnp.delivery.puppetlabs.net' back to vmpooler for VM destruction
Spent 0.44 seconds cleaning up

You can reproduce this run with:
/Users/matthaus/src/puppetserver/vendor/bundle/ruby/2.4.0/bin/beaker --debug --root-keys --no-color --repo-proxy --preserve-hosts onfailure --type aio --helper acceptance/lib/helper.rb --options-file acceptance/config/beaker/options.rb --load-path acceptance/lib --config acceptance/config/beaker/jenkins/redhat7-64m-64a.cfg --keyfile /Users/matthaus/.ssh/id_rsa-acceptance --pre-suite acceptance/suites/pre_suite/foss --tests acceptance/suites/tests/metrics/collect_default_metrics.rb

Important ENV variables that may have affected your run:
    GEM_HOME		/Users/matthaus/src/puppetserver/vendor/bundle/ruby/2.4.0
    GEM_PATH
    RUBYLIB		/usr/local/lib/ruby/site_ruby/2.4.0:/Users/matthaus/src/puppet/lib:/Users/matthaus/src/facter/lib:/Users/matthaus/src/hiera/lib
    PATH		/Users/matthaus/src/puppetserver/vendor/bundle/ruby/2.4.0/bin:/usr/local/opt/ruby/bin:/Users/matthaus/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/munki:/opt/puppetlabs/bin:/Library/TeX/texbin
    home		/Users/matthaus
Beaker completed successfully, thanks.
```

**Comment by lindboe** [comment]
Yeah @justinstoller or @Magisus I'm not sure that this is testing anything that needs to be tested at this level. What would you think about either deleting this or adding similar smoke coverage to clojure tests?

**Comment by justinstoller** [comment]
I'm fine deleting this test, this isn't testing anything that isn't tested individually at other levels.

**Comment by Magisus** [comment]
🔥 🔥 🔥

**Comment by haus** [comment]
Updated.

**Pull request merged**
