### PR TITLE
(maint) Update ps-version to 2.6.1-SNAPSHOT for release

### PR DESCRIPTION
**Pull request by haus**

### CODE REVIEW

**Comment by Magisus** [comment]
Oh right, I guess we still don't have Travis for this branch because the config was updated elsewhere. Awkward :P

**Comment by haus** [comment]
I can pull the travis change in (after release?) if we intend to keep the branch around.

**Comment by haus** [comment]
or now to make sure the change didn't explode anything

**Comment by justinstoller** [comment]
if you could open another PR, that'd be ideal

**Comment by haus** [comment]
TRAVIS?

**Pull request merged**
