### PR TITLE
(maint) Add MAINTAINERS file

### PR DESCRIPTION
**Pull request by kylog**
Hi @KevinCorcoran @cprice404 @camlow325  @rlinehan @justinstoller @haus @jpinsonault:

Anticipating some possible questions:

* This PR add a MAINTAINERS file to document who is maintaining this repo. The list of people started with the top 10 PR mergers in the last year, plus a little conversation here https://github.com/puppetlabs/kylo_scratchpad/pull/1/files#r76404602
* If the list seems wrong, let's feel free to edit it.
* The format of the file is documented here: http://github.com/puppetlabs/maintainers
* And I used https://rubygems.org/gems/maintainers to construct the file
* I pushed the PR branch to the puppetlabs space (rather than mine) so that all parties can edit collaboratively as needed
* Note that this is a public repo. The email and name fields are optional here. As a starting point, I pre-populated them with the publicly available names/emails available for all of us on github (but took bogus or non-puppet emails as an indication that you may not want to share your puppet.com email). Please feel free to edit your email and name fields for any reason.

### CODE REVIEW

**Comment by justinstoller** [comment]
Thanks @kylog ! I've added my work email. 👍

**Comment by camlow325** [comment]
👍 I added one more commit to scrub the old list of maintainer names from the README since we'll have them in the MAINTAINERS file now.

**Comment by jpinsonault** [comment]
Added my email

**Comment by cprice404** [comment]
:see_no_evil:

**Comment by rlinehan** [comment]
lgtm

**Comment by kylog** [comment]
Any more signoffs we want on this sucker before someone hits merge (or squash-and-merge)?

**Comment by haus** [comment]
q-beautiful

**Pull request merged**
