### PR TITLE
Add maintainers section

### PR DESCRIPTION
**Pull request by karenvdv**

### CODE REVIEW

**Comment by erikPrime** [comment]
:+1:

**Comment by rlinehan** [comment]
I hate to be that person, but should this be targeted at stable? or is it okay to just have the maintainers section in our README on master? (we'll be merging down soon anyway, so it probably doesn't matter a ton)

**Comment by erikPrime** [comment]
@rlinehan I kind of thought that if we got this in soon, it would get merged down...

**Comment by rlinehan** [comment]
@erikPrime yeah, that seems reasonable. 👍

**Pull request merged**
