### PR TITLE
(MAINT) bump version to next snapshot

### PR DESCRIPTION
**Pull request by jpinsonault**
Move the version up to the next snapshot version

### CODE REVIEW

**Comment by justinstoller** [comment]
This process seems broken, I don't remember it being this tedious.

**Comment by Magisus** [comment]
It's also quite different from the other clojure lib processes.

**Comment by jpinsonault** [comment]
agreed all around

**Comment by justinstoller** [comment]
> agreed all around

but it looks like it is what it is

https://confluence.puppetlabs.com/display/systemsEngineering/Releasing+a+new+version+of+Puppet+Server#ReleasinganewversionofPuppetServer-Updateversionnumberinsource

Describes doing just this.

**Comment by jpinsonault** [comment]
yep... 👍

**Comment by Magisus** [comment]
Probably fairly easy to fix with the jobs we have for other stuff (including open source stuff).

**Comment by justinstoller** [comment]
You have a doc where you're adding pain points, Maggie? Did this make it into it    (:

**Comment by Magisus** [comment]
No doc yet, I have some steps that'll become tickets in a notebook. I think this is slightly orthogonal to the promotion problem, since we don't want to release puppetserver, just do a voom build. But I can make a ticket along the way.

**Comment by MosesMendoza** [comment]
Hi Moses

**Comment by justinstoller** [comment]
Touche, in my head they were notes about CI pain points/lack of automation. Makes sense to keep it scoped to promotion.

**Comment by justinstoller** [comment]
@MosesMendoza --

**Comment by Magisus** [comment]
Ah, but in hipchat his handle is just @moses

**Pull request merged**
