### PR TITLE
(maint) Fix .travis.yml merge up mistake

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
maybe?

**Comment by justinstoller** [comment]
now with openjdk rather than oraclejdk.

**Comment by Magisus** [comment]
Question though, what is the status of oraclejdk vs openjdk for us?

**Comment by Magisus** [comment]
Cool good to know.

**Comment by justinstoller** [comment]
good lord travis

**Pull request merged**
