### PR TITLE
(SERVER-2054) [#puppethack] Add support for PUT /puppet/v3/facts

### PR DESCRIPTION
**Pull request by Sharpie**
This patch adds a comidi handler to the routing tree of the MasterService that
responds to PUT requests for `/puppet/v3/facts`.

### CODE REVIEW

**Comment by Sharpie** [comment]
Adding "DO NOT MERGE" as the test attached to this PR will fail until puppetlabs/puppet#6434 is merged and the `ruby/puppet` submodule is updated to bring that changeset in.

**Comment by Sharpie** [comment]
Another thing that might be worth considering is whether we want a default auth rule that allows access to this endpoint. The original docs from the `puppet facts upload` face state that auth.conf has to be modified to allow the upload.

However, it would be pretty easy to add something to the default ruleset that allows nodes to upload their own facts:

```
puppet_authorization::rule {'node fact upload':
  ensure               => $ensure,
  match_request_path   => '^/puppet/v3/facts/([^/]+)$',
  match_request_type   => 'regex',
  match_request_method => 'put',
  allow                => '$1',
  sort_order           => 601,
  path                 => '/etc/puppetlabs/puppetserver/conf.d/auth.conf',
  notify               => $_puppetserver_service,
}
```

**Comment by justinstoller** [comment]
Good point, Charlie. Will you update https://github.com/puppetlabs/puppetserver/blob/master/ezbake/config/conf.d/auth.conf with the equivalent of that Puppet code? We will also need to record somewhere that there will be a puppet_enterprise module change as well in the process of promoting this into PE.

**Comment by Sharpie** [comment]
Rebased onto master, fixed a merge conflict, and updated ezbake auth.conf.

**Comment by ericldelaney** [comment]
@justinstoller could you please review this.

This is the other half of the PUP-8232 https://github.com/puppetlabs/puppet/pull/6434 which probably wan't pass travis until PUP-8232 is merged and we rerun travis.

**Comment by justinstoller** [comment]
fyi, we're blocking this PR on puppetlabs/puppet#6434 which is currently going back and forth between @Sharpie and @joshcooper . Once that is merged we'll be open to merging this. IIRC, we're hoping to have this in for the Platform 5.5 release which needs its code landed ~ end of this week.

**Comment by justinstoller** [comment]
Now that https://github.com/puppetlabs/puppet/pull/6434 has been merged it should be brought into puppetserver as a new submodule after it has passed agent's CI. Once that happens we can re-kick travis and should see these tests go green!

**Pull request merged**
