### PR TITLE
(maint) Update Puppet Server for gzip suffix changes

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Review by mwaggett — COMMENTED** [review]
changes look good, but I think this should target 6.x and the commit message should reference the relevant ticket and include a little more detail about why we're making this change.

**Comment by Magisus** [comment]
The ticket is a PE ticket, so not sure how I feel about referencing it. Agree that we could say this changed with the jetty update though.

**Comment by mwaggett** [comment]
ugh. well we did decide we were okay with referencing internal tickets for r10k.. ¯\_(ツ)_/¯

**Comment by justinstoller** [comment]
Updated

**Review by mwaggett — APPROVED** [review]

**Pull request merged**
