### PR TITLE
Merge 5.1.x at e48e4050 into master

### PR DESCRIPTION
**Pull request by adrienthebo**
oh god how did this get here I am not good with computer

### CODE REVIEW

**Comment by adrienthebo** [comment]
I'M NOT TOUCHING ANYTHING THIS TIME

**Comment by Magisus** [comment]
It looks like the contents of the submodule changed, but the beaker options file was not updated. Are we going to let the Jenkins job resolve this?

**Comment by adrienthebo** [comment]
@Magisus I just compared the beaker options file and the ruby/puppet submodule and both of those appear to me as having the same revision for both master and this branch. How did you determine that the beaker options file was not updated?

**Comment by adrienthebo** [comment]
For context this is what I'm seeing as the last change to options.rb:

```
commit ee1f021bdb0029ba595fd730a28e26f3f36b5a8e (upstream/master, upstream/HEAD, master)
Author: Jenkins CI <ci@puppet.com>
Date:   Wed Oct 11 09:11:25 2017 +0000

    (maint) update puppet submodule version and pins

diff --git a/acceptance/config/beaker/options.rb b/acceptance/config/beaker/options.rb
index a65a6e58..cba4e22e 100644
--- a/acceptance/config/beaker/options.rb
+++ b/acceptance/config/beaker/options.rb
@@ -11,5 +11,5 @@
  "puppetserver-confdir"=>"/etc/puppetlabs/puppetserver/conf.d",
  "puppetserver-config"=>
   "/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf",
- :puppet_version=>"5.3.2.66.g0ff9cf7",
- :puppet_build_version=>"ac142bea60e5ce29efc52b12a9969c789b2ef15f"}
+ :puppet_version=>"5.3.2.68.g222c118",
+ :puppet_build_version=>"6661a1c9ab7d0ac15580c310652862e4e3321961"}
```

**Comment by Magisus** [comment]
I'm not even sure, the github UI is funky. I'm gonna go ahead and merge this, if something needs to updated there, it'll happen in Jenkins.

**Comment by adrienthebo** [comment]
#yolo

**Pull request merged**
