### PR TITLE
(RE-7945) Add SLES 12 to puppetserver pipelines

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
I have tested this with Ubuntu 15.10 and Centos 6, and I'm currently testing SLES 12.

**Comment by cprice404** [comment]
:see_no_evil: +1 when our CI jobs are green again

**Comment by melissa** [comment]
Ooops, this also needs two commits that were merged into the master branch. I've cherry-picked them to include them in this PR.

**Comment by melissa** [comment]
This passes for SLES 12 x86_64

**Comment by melissa** [comment]
Herm, it looks like rubocop is failing to install because there is an insufficient version of ruby available.

**Comment by justinstoller** [comment]
@melissa checkout the PR I linked above, it has a fix for that

**Comment by melissa** [comment]
@cprice404 checks have gone green! I'd love to get this in this morning, so we can also get https://github.com/puppetlabs/ci-job-configs/pull/1616 in and watch the jobs today/tomorrow to make sure everything is golden

**Comment by cprice404** [comment]
@melissa I'm happy to merge it; one quick question first - I notice this is targeted at stable.  Is there a specific release you're expecting it to go into?

**Comment by melissa** [comment]
Not a specific release, just a release in the near future. Would you rather this go out in a later release? We already have puppet-agent for sles available in the public repos, so we're not blocked on that

**Comment by cprice404** [comment]
@melissa just making sure that you weren't counting on it in some specific release.  stable is fine.  We'll hopefully be doing a 2.6.0 release from 'master' in a few weeks (was planning to ping you all about that soon), so this can ship in that release.  we'll just merge up to master from stable.

**Comment by melissa** [comment]
Awesome, thanks!!

**Pull request merged**
