### PR TITLE
(CPR-591) Add build scripts for puppet6-nightly containers

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by justinstoller** [comment]
Should we be gating these on the azure pipeline issues?

**Comment by underscorgan** [comment]
https://github.com/puppetlabs/puppetserver/pull/1836 should fix the windows issues, but might be good to get that in and merged up to verify this doesn't break any windows-y things.

**Comment by underscorgan** [comment]
depends on https://github.com/puppetlabs/puppet_docker_tools/pull/30

**Comment by underscorgan** [comment]
That's been merged and a new gem's been released, so this is ready to go!

**Pull request merged**
