### PR TITLE
(maint) Update ezbake to 1.6.5

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
Test packaging job kicked off at https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_various-packaging-jobs_packaging-os-clj_lein-ezbake-generic/261/

**Comment by justinstoller** [comment]
I only see an artifacts directory under the link you provided, but on a build from [yesterday](http://builds.delivery.puppetlabs.net/puppetserver/5.1.5.SNAPSHOT.2017.11.14T1048/) I see artifacts, repos, and repo_configs directories.

Is this expected? I haven't followed through with Beaker's expectations, I can do that tomorrow.

**Comment by melissa** [comment]
It looks like something strange is happening when ezbake builds are getting kicked off locally. It shouldn't impact the pipelines themselves. I'm seeing the same thing with ezbake 1.6.3

**Comment by justinstoller** [comment]
Point of order, I don't think a .z bump of our internal tooling should require two approvals. Someone tell me if they disagree.

**Pull request merged**
