### PR TITLE
Merge 5.0.x at ed415838 into master

### PR DESCRIPTION
**Pull request by adrienthebo**

### CODE REVIEW

**Comment by adrienthebo** [comment]
I'm going to run some acceptance smoke tests on this for sanity.

**Comment by adrienthebo** [comment]
This change might trigger failures in CI because the puppet-agent builds that we've been pinned to look to have been cleaned up. However this could be a really good chance to verify https://github.com/puppetlabs/puppetserver/pull/1458.

**Comment by justinstoller** [comment]
Since this is a merge up does that mean that 5.0.x will also start failing?

**Comment by camlow325** [comment]
> Since this is a merge up does that mean that 5.0.x will also start failing?

I don't think so since this PR preserves the pins for puppet-agent and the Ruby Puppet submodule which are already on the master branch - not bringing the newer ones in from the 5.0.x branch.

**Comment by justinstoller** [comment]
> I don't think so since this PR preserves the pins

I guess I should ask, if these pins are broken, and doing this merge up will cause a CI run that changes no code but we know is going to fail... Why don't we change those pins in 5.0.x and then do the merge up?

**Comment by justinstoller** [comment]
Sounds like I read this wrong

**Pull request merged**
