### PR TITLE
(DO NOT MERGE) (RE-8457) Update to ship to puppet5 repos

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
This is dependent on https://github.com/puppetlabs/ezbake/pull/420, and will also need an ezbake bump once that change is merged and a new ezbake release is cut

**Comment by melissa** [comment]
Do you have a 'do not merge' label, or something of the sort?

**Comment by adrienthebo** [comment]
@melissa @camlow325 does this need to be merged before we can merge master into stable?

**Comment by melissa** [comment]
I hope not... After talking with @geoffnichols, this should get merged after puppetserver 5.0.0 is shipped. I can retarget this PR if necessary

**Comment by camlow325** [comment]
@melissa Just checking in on this one.  We still don't want to merge this yet, right (since the corresponding ezbake PR hasn't landed yet)?  When this is eventually ready for merge, do you think it would be better to target the 5.0.x branch (our new "stable" branch cut from the "5.0.0" release) and then merge up from there to the master branch?

**Comment by melissa** [comment]
Yes, this PR should target the 5.0.x branch. I don't believe that branch existed when I created this PR. I'll check in once the ezbake changes have landed and been released

**Comment by melissa** [comment]
@justinstoller should this PR be targeted at `master` or `5.0.x`?

**Comment by justinstoller** [comment]
Our numbered branches keep moving forward (with a small delta between them), so if this is going to have continued work it might be best to work against master.

Since we release every four weeks it isn't a huge deal, I think, to get into master and at most wait a month to see it released, unless it is (: in that case I'd still work against master and retarget it to whatever.whatever.x when the work is done.

**Pull request closed without merging**
