### PR TITLE
(MAINT) update to tk-auth 0.6.1

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by camlow325** [comment]
👍

**Comment by rlinehan** [comment]
Just as an FYI, this will break acceptance tests on master too until I get a PR in to fix the tests in stable and then we presumably merge up?

**Comment by cprice404** [comment]
@rlinehan if you think you will have a fix for the acceptance soon, we can wait on this.

**Comment by rlinehan** [comment]
The PR for the fix is up already - #1072
>
>

**Comment by erikPrime** [comment]
Merged #1072, This looks good to me, merging this as well.

**Pull request merged**
