### PR TITLE
(RE-8457) Update to ship to puppet5 repos

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
Tested with 
```
APT_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
APT_SIGNING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
APT_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
DMG_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
DMG_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
GEM_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
IPS_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
MSI_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
MSI_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
NUGET_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
P5P_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
SWIX_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
SWIX_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
SVR4_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
TAR_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
TAR_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
YUM_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
YUM_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
INTERNAL_GEM_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
INTERNAL_NEXUS_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
INTERNAL_STICKLER_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
rake pl:jenkins:uber_ship
```
Had to manually pull packages from http://builds.puppetlabs.lan/puppetserver/5.1.2.SNAPSHOT.2017.09.26T2349/artifacts/ because we aren't tagging dev builds (this will be an issue with nightly ships unless we create a billion dev tags for the purpose of shipping artifacts to nightlies).


Gave me:
```
[root@oqcod8kmrz9f4px ~]# find /opt/downloads /opt/repository /opt/tools -type f | sort
/opt/downloads/eos/puppet5-nightly/4/i386/puppet-agent-5.0.1.496.g26d807b-1.eos4.i386.swix
/opt/downloads/eos/puppet5-nightly/4/i386/puppet-agent-5.0.1.496.g26d807b-1.eos4.i386.swix.asc
/opt/downloads/mac/puppet5-nightly/10.10/x86_64/puppet-agent-5.0.1.496.g26d807b-1.osx10.10.dmg
/opt/downloads/mac/puppet5-nightly/10.12/x86_64/puppet-agent-5.0.1.496.g26d807b-1.osx10.12.dmg
/opt/downloads/puppet/puppetserver-5.1.2.SNAPSHOT.2017.09.26T2349.tar.gz
/opt/downloads/windows/puppet5-nightly/puppet-agent-5.0.1.496.g26d807b-x64.msi
/opt/repository/yum/puppet5-nightly/cisco-wrlinux/5/x86_64/puppet-agent-5.0.1.496.g26d807b-1.cisco_wrlinux5.x86_64.rpm
/opt/repository/yum/puppet5-nightly/el/5/i386/puppet-agent-5.0.1.496.g26d807b-1.el5.i386.rpm
/opt/repository/yum/puppet5-nightly/el/5/x86_64/puppet-agent-5.0.1.496.g26d807b-1.el5.x86_64.rpm
/opt/repository/yum/puppet5-nightly/el/6/i386/puppet-agent-5.0.1.496.g26d807b-1.el6.i386.rpm
/opt/repository/yum/puppet5-nightly/el/6/i386/puppetserver-5.1.2-0.1SNAPSHOT.2017.09.26T2349.el6.noarch.rpm
/opt/repository/yum/puppet5-nightly/el/6/x86_64/puppetserver-5.1.2-0.1SNAPSHOT.2017.09.26T2349.el6.noarch.rpm
/opt/repository/yum/puppet5-nightly/el/7/x86_64/puppet-agent-5.0.1.496.g26d807b-1.el7.x86_64.rpm
/opt/repository/yum/puppet5-nightly/el/7/x86_64/puppetserver-5.1.2-0.1SNAPSHOT.2017.09.26T2349.el7.noarch.rpm
/opt/repository/yum/puppet5-nightly/fedora/f24/i386/puppet-agent-5.0.1.496.g26d807b-1.fedoraf24.i386.rpm
/opt/repository/yum/puppet5-nightly/fedora/f24/x86_64/puppet-agent-5.0.1.496.g26d807b-1.fedoraf24.x86_64.rpm
/opt/repository/yum/puppet5-nightly/fedora/f25/i386/puppet-agent-5.0.1.496.g26d807b-1.fedoraf25.i386.rpm
/opt/repository/yum/puppet5-nightly/fedora/f26/x86_64/puppet-agent-5.0.1.496.g26d807b-1.fedoraf26.x86_64.rpm
/opt/repository/yum/puppet5-nightly/sles/11/i386/puppet-agent-5.0.1.496.g26d807b-1.sles11.i386.rpm
/opt/repository/yum/puppet5-nightly/sles/11/x86_64/puppet-agent-5.0.1.496.g26d807b-1.sles11.x86_64.rpm
/opt/repository/yum/puppet5-nightly/sles/12/x86_64/puppet-agent-5.0.1.496.g26d807b-1.sles12.ppc64le.rpm
/opt/repository/yum/puppet5-nightly/sles/12/x86_64/puppet-agent-5.0.1.496.g26d807b-1.sles12.x86_64.rpm
/opt/repository/yum/puppet5-nightly/sles/12/x86_64/puppetserver-5.1.2-0.1SNAPSHOT.2017.09.26T2349.sles12.noarch.rpm
/opt/tools/freight/apt/jessie/puppet5-nightly/puppet-agent_5.0.1.496.g26d807b-1jessie_amd64.deb
/opt/tools/freight/apt/jessie/puppet5-nightly/puppet-agent_5.0.1.496.g26d807b-1jessie_i386.deb
/opt/tools/freight/apt/jessie/puppet5-nightly/puppetserver_5.1.2-0.1SNAPSHOT.2017.09.26T2349jessie_all.deb
/opt/tools/freight/apt/stretch/puppet5-nightly/puppetserver_5.1.2-0.1SNAPSHOT.2017.09.26T2349stretch_all.deb
/opt/tools/freight/apt/trusty/puppet5-nightly/puppet-agent_5.0.1.496.g26d807b-1trusty_i386.deb
/opt/tools/freight/apt/wheezy/puppet5-nightly/puppet-agent_5.0.1.496.g26d807b-1wheezy_amd64.deb
/opt/tools/freight/apt/wheezy/puppet5-nightly/puppet-agent_5.0.1.496.g26d807b-1wheezy_i386.deb
/opt/tools/freight/apt/xenial/puppet5-nightly/puppet-agent_5.0.1.496.g26d807b-1xenial_amd64.deb
/opt/tools/freight/apt/xenial/puppet5-nightly/puppet-agent_5.0.1.496.g26d807b-1xenial_i386.deb
/opt/tools/freight/apt/xenial/puppet5-nightly/puppetserver_5.1.2-0.1SNAPSHOT.2017.09.26T2349xenial_all.deb
```

**Comment by melissa** [comment]
@mwaggett the tar sign task failed, because:
```
File.exist?("pkg/#{Pkg::Config.project}-#{Pkg::Config.version}.tar.gz") or fail "No tarball exists. Try rake package:tar?"
```

`Pkg::Config.version` here doesn't equal `5.1.2.SNAPSHOT.2017.09.26T2349` because of how ezbake versions artifacts.

**Comment by mwaggett** [comment]
@melissa Did you delete your comment about the tar sign task? I know you said it would be taken care of with the artifactory work, but I'm wondering if it could be worth just checking for *.tar.gz so that it doesn't fail with weird ezbake versioning?

**Comment by mwaggett** [comment]
unrelated to this pr though, which lgtm.

**Comment by melissa** [comment]
I did delete that comment. I decided it's unrelated to this work. I added it to the comment about updating the sign task.

**Comment by melissa** [comment]
I found a few bugs in the packaging repo. This shouldn't be merged until those are resolved

**Comment by melissa** [comment]
I'd like to see https://cinext-jenkinsmaster-enterprise-prod-1.delivery.puppetlabs.net/view/pe-integration/view/pe-2018.1.x/job/enterprise_pe-acceptance-tests_integration-system_pe_full-pre-upgrade_nightly_2018.1.x/ finish green, but currently the failure looks unrelated to this change on puppet-agent.

**Comment by justinstoller** [comment]
@melissa should this be merged prior to the next release (5.1.4) or should this hold off until after?

**Comment by melissa** [comment]
it's up to you. There may still be some bugs in this update that haven't been flushed out. So if you're on a time crush, I'd say wait

**Comment by justinstoller** [comment]
I merged this without travis running since it only updates build_defaults.yaml file (which won't be tested by travis anyways). A passing travis run became a blocker after this PR was opened and travis wasn't easily picking up that it should run this PR (see my attempt to trigger it by closing and reopening the PR).

**Pull request merged**
