### PR TITLE
(SERVER-3021) Add `lein-nvd` security scanner

### PR DESCRIPTION
**Pull request by mwaggett**
This commit adds the `lein-nvd` security scanner and adds a vulnerability check
to the set of checks that Travis runs on each PR.

### CODE REVIEW

**Comment by mwaggett** [comment]
My local run uncovered some vulnerabilities, so not sure if we want to merge this before resolving those, but I wanted to get this up to test that Travis will actually run the check.

**Comment by Magisus** [comment]
I heard some other teams talking about adding some exceptions too, so if we wanted to get this in and add those for the ones we either know we can't fix (like JRuby's BouncyCastle) or are planning to fix later, I think that's an option too?

**Comment by mwaggett** [comment]
yep, I just want us to make those decisions consciously.

**Comment by mwaggett** [comment]
woooo, it works in Travis lol

**Comment by Magisus** [comment]
Looks like this is causing some issues for ezbake... probably because it has that separate deps profile?

**Comment by mwaggett** [comment]
woo finally green!

**Review by Magisus — APPROVED** [review]

**Pull request merged**
