### PR TITLE
[REVIEW ONLY - DO NOT MERGE] (QA-2605) Extract QA test libs from puppetserver into master_manipulator

### PR DESCRIPTION
**Pull request by kurtwall**
This commit removes QA library code from puppetserver. This PR should not be merged until [master manipulator PR #18](https://github.com/puppetlabs/master_manipulator/pull/18) gets merged and a new master_manipulator gem with the corresponding changes is available.

### CODE REVIEW

**Comment by kurtwall** [comment]
Very much a WIP.

**Comment by erikPrime** [comment]
Looks good to me.

**Comment by cprice404** [comment]
What's the status on this one?

**Comment by kurtwall** [comment]
@cprice404 This is still review-only. There's another PR that has to merge into master_manipulator before this one can be merged. The other PR is waiting on me to write spec tests.

**Comment by cprice404** [comment]
@kurtwall is this still going to happen or should we close it

**Comment by kurtwall** [comment]
@cprice404 This is still a thing AFAIC. I'm writing the spec tests for the extensive changes to  master_manipulator now. When they're done and passing, the changes to MM will get merged. Then we can cut a new gem, push it to rubygems, and resume the work on this PR to sanitize puppetserver's test code. On the other hand, it will take several more weeks, optimistically, before I'll be at that point. In the interests of being tidy, I can close this and submit a fresh PR at that time. Your call.

**Comment by cprice404** [comment]
I don't care if it stays open if you are actually still planning to land it... just assumed that with re-org you might not get an opportunity.

**Comment by kurtwall** [comment]
Fair observation. I might not, but I regard it as unfinished work that I need to finish. I think it might make everyone's life post-The Great Reorgalypse a little easier vis-â-vis maintaining the testing codebase.

**Comment by kurtwall** [comment]
@cprice404 Do you object to me closing this PR and revisiting it in the future after all the dust from The Great Reorgalypse has settled?

**Comment by cprice404** [comment]
@kurtwall no, if you don't have reasaon to believe that this will get some attention soon, I'd prefer that you close it.

**Comment by kurtwall** [comment]
Closing this PR. I won't get back to the underlying work for quite some time, if ever.

**Pull request closed without merging**
