### PR TITLE
(maint) Enable Java 17 testing

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Review by steveax — APPROVED** [review]
👍

**Comment by jonathannewman** [comment]
We aren't supporting java 8 for 8.x, so I think we can drop that version entirely.

**Comment by jonathannewman** [comment]
We are using lein 2.9.10 now, so I think we can update `lein: 2.9.1` to that in the travis file too?

**Comment by justinstoller** [comment]
Last push had everything working. Rebase to clean up the commits and add the ticket number. Hopefully ready to go after travis finishes.

**Comment by jonathannewman** [comment]
LGTM!

**Pull request merged**
