### PR TITLE
(maint) Bring in updated clj-parent

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
Should I also manually update the puppet submodule?

**Comment by Sharpie** [comment]
A submodule update would be a good idea as it should unblock testing on other open PRs.

**Comment by Magisus** [comment]
The agent is almost done promoting, PEZ seems gummed up, give me a second to look into it. It'd be easier to just run the submodule update job once that passes.

**Comment by justinstoller** [comment]
I updated the submodule, but it only. See the commit message about preferring the automated bump for acceptance tests. Happy to remove the commit if the agent will promote some time soon.

**Comment by Magisus** [comment]
Expecting a promotion in the next 20 minutes. We'll see who gets there first, Travis or Jenkins :)

**Comment by justinstoller** [comment]
Mmm... neither travis nor that agent promotion seemed to have much haste about them. It looks like there's some new failures with the clj-parent bump wrt client http metrics w/ FIPS enabled. Are those expected?

**Comment by Magisus** [comment]
Not expected by me 🤷‍♀

**Comment by Magisus** [comment]
Got the submodule and agent ref updated via the Jenkins job.

**Comment by Magisus** [comment]
I'm seeing the failures locally without the clj-parent update but with the submodule bump.

**Comment by justinstoller** [comment]
Which ever goes in first between this and https://github.com/puppetlabs/puppetserver/pull/2154 is going to cause the other to have to rebase and I won't be around if its me. I'm just going to close this and maybe we can update to 4.2.0 in the other PR?

**Comment by Magisus** [comment]
Sounds good, I'll push that if Charlie doesn't get there first.

**Pull request closed without merging**
