### PR TITLE
(PUP-3827) Update default_rules test to search for 500 rather than 400

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
Running tests locally

**Comment by justinstoller** [comment]
Supersedes #1110

**Comment by cprice404** [comment]
+1

**Comment by erikPrime** [comment]
:eyes: good to me.  Awaiting results of @justinstoller 's local run...

**Comment by justinstoller** [comment]
OMG, it finally passed

**Pull request merged**
