### PR TITLE
(maint) Update ezbake to pick up systemd for xenial

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by geoffnichols** [comment]
👍 , pending Travis

**Comment by underscorgan** [comment]
This resulted in puppetserver packages on trusty that won't start with java 7. DO NOT MERGE.

**Comment by underscorgan** [comment]
This works now that I built it with the correct java.

**Comment by KevinCorcoran** [comment]
Is there a JIRA ticket about adding Xenial support which could be mentioned in the commit message?

👍 otherwise

**Comment by underscorgan** [comment]
@KevinCorcoran there doesn't seem to be one for the foss server stuff, you ok with this staying as a maint since it's a dependency bump?

**Comment by rlinehan** [comment]
I'm cool with this being maint, also would like to get this in before merging down master to stable, which I'd like to do today. So 👍.

**Pull request merged**
