### PR TITLE
(maint) Remove default `set -e ` for gh actions shell

### PR DESCRIPTION
**Pull request by underscorgan**
Skipped release build without failing the job at https://github.com/puppetlabs/puppetserver/runs/550391873?check_suite_focus=true

### CODE REVIEW

**Comment by underscorgan** [comment]
@mwaggett that looks like it failed in java11 puppetserver tests which is not related to this fix?

**Comment by mwaggett** [comment]
@underscorgan That push job that's failing looks like a docker thing? Honestly not sure what that job is or why it's running.

**Comment by underscorgan** [comment]
I think that push job got tied to this somehow but is pulling from the branch I initially had pushed upstream to test out the actions stuff, it's pulling from a branch/commit that no longer exist, so I think it should be ignored

**Comment by Magisus** [comment]
Does this only apply to master? I've lost track of where we do Docker stuff.

**Comment by underscorgan** [comment]
yep, only master

**Pull request merged**
