### PR TITLE
(DOCUMENT-729) Note static_catalogs setting behavior.

### PR DESCRIPTION
**Pull request by gguillotte**
Add `static_catalogs` to the puppet.conf setting differences doc to clarify when and how it's respected.

### CODE REVIEW

**Comment by justinstoller** [comment]
I see that related PRs have been posted for older versions of Puppet, should this be targeted at older branches of server as well?

**Comment by Magisus** [comment]
How long has this setting been a thing (and behaved this way)? If "forever", I'm with Justin, let's target at 2.x (or 5.1.x).

**Comment by gguillotte** [comment]
I targeted at master before I knew that we were back to doing z-version branches, so I'm happy to retarget to other branches. For docs purposes, this change needs to be made to any version branches where it's relevant.

**Comment by justinstoller** [comment]
I'd say retarget to the oldest branch that we need these changes in, and then we can merge those changes up to the latest release (I don't know about every intervening release). At least that's the usual protocol. This is a pretty trivial diff, so I'm not too concerned.

**Comment by gguillotte** [comment]
ha ha NOPE, that ain't gonna work

**Pull request closed without merging**
