### PR TITLE
(MAINT) merge up from stable 2016-08-25

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by cprice404** [comment]
@gguillotte would you mind reviewing the docs changes here when you get a sec?  Not super urgent, but would like to get this in for @melissa sometime in the next few days.

**Comment by gguillotte** [comment]
@cprice The docs changes in here LGTM. Since you and @camlow325 already +1'd PR #1185 on resource_types, I'm also OK with adding that (if it's an option) if there isn't another merge up planned.

**Comment by cprice404** [comment]
@gguillotte I just pushed commits with another merge that adds in the changes from #1185

**Comment by gguillotte** [comment]
@cprice404 Now I'm 💯  👍

**Comment by cprice404** [comment]
@gguillotte added another one to get the link fixes

**Comment by cprice404** [comment]
Cool.  everything else in the diff looks like @melissa , so, @melissa do you want to review and push buttons?

**Comment by melissa** [comment]
Beautiful! I'll merge once travis is green

**Comment by melissa** [comment]
TRAVIS YOU ARE SO SLOW!

**Pull request merged**
